# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        dc:
          - ldc-latest
          - dmd-latest

    runs-on: ${{matrix.os}}

    steps:
      - name: Setup D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Checkout source
        uses: actions/checkout@v2

      - name: 'Build'
        run: |
          # Build the project, with its main file included, without unittests
          dub build
